server:
  port: 9000
spring:
  application:
    name: service-zuul
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
zuul:
  # 补充
#  routes:
#    filmapi:
#      path: /filmapi/film/**
#      serviceId: service-film
ribbon:
  eureka:
    enabled: true
